castorini/pygaggle

pygaggle/data/__init__.py
pygaggle/data/msmarco.py
pygaggle/data/relevance.py
pygaggle/data/unicode.py
pygaggle/model/decode.py
pygaggle/model/evaluate.py
pygaggle/rerank/base.py
pygaggle/run/evaluate_kaggle_highlighter.py
pygaggle/run/evaluate_passage_ranker.py
pygaggle/settings.py
setup.py

Tested on a subset of 50 questions (1000 passages each) on colab (P100): https://colab.research.google.com/drive/1C-0U40wCUbDUObWReBYkeIBLgqJeKCuO
It takes about 16-17 minutes. So can potentially scale it up to 1000ish examples when having URAs replicate it. I will also entirely replicate the results entirely across multiple GPUs/TPUs as and when I add support for it!
m̶r̶r̶@̶1̶0̶ ̶0̶.̶3̶6̶4̶7̶6̶9̶8̶4̶1̶2̶6̶9̶8̶4̶1̶3̶ ̶v̶s̶ ̶@̶r̶o̶d̶r̶i̶g̶o̶n̶o̶g̶u̶e̶i̶r̶a̶4̶'̶s̶ ̶r̶u̶n̶.̶m̶o̶n̶o̶b̶e̶r̶t̶.̶d̶e̶v̶.̶s̶m̶a̶l̶l̶.̶t̶s̶v̶ ̶s̶c̶o̶r̶i̶n̶g̶ ̶m̶r̶r̶@̶1̶0̶:̶ ̶0̶.̶3̶5̶7̶6̶9̶0̶4̶7̶6̶1̶9̶0̶4̶7̶6̶3̶ ̶o̶n̶ ̶t̶h̶e̶s̶e̶ ̶5̶0̶ ̶q̶u̶e̶s̶t̶i̶o̶n̶s̶.̶ ̶(there was something wrong with the sample, reinvestigating now) This is potentially due to the tokenization difference (here we just use encode_plus that …

MSMARCO support: monoBERT

---

pygaggle/model/evaluate.py
pygaggle/rerank/transformer.py

When evaluating MS-MARCO/other datasets, I think it is better to score all samples regardless of whether or not the sample has a label. They could not have labels for instance if it failed to retrieve relevant passage in the first round of ranking. Setting recall with zero_division equivalent to 0 instead of 1 should score this right (also consistent with msmarco_eval.py).
This issue also fixes a bug with the T5 decoder. Since we want the output to be over the T/F label distribution of the first decoder output, and not the second (which is what the code was previously doing). Note that the way that was done is not all that bad in terms of performance surprisingly. As a result of this fix, T5 outperforms all other models in all regards in CovidQA.
natural question:
precision@1 …

Fix Zero div and T5 decoding

---

docs/experiments-msmarco-passage.md

Replication Status:
Success (No issues)
Environment:
OS: Ubuntu18.04 LTS
Python: 3.7.6
Pytorch: 1.5.0
GPU: Tesla P4
CUDA: 10.2
Replication Results:
monoBERT:
monoT5:

Add replication for MS MARCO passage experiment

---

docs/experiments-msmarco-passage.md

Update MS MARCO Passage Replication Log

---

docs/experiments-msmarco-passage.md

Environment
OS: Ubuntu 18.04.1 LTS
Java: openjdk 11.0.7 2020-04-14
Python: 3.6.9
monoBERT:
monoT5:

Replicated MS MARCO passage ranking experiment

---

.gitmodules

Rename, change `eval/` to `eval` in the path. Seems to only work for me if I do this

Fix submodule name to be consistent with pyserini, minor changes to get it to work

---

docs/experiments-CovidQA.md
pygaggle/data/relevance.py
pygaggle/data/segmentation.py
pygaggle/rerank/bm25.py

As discussed in #70, recent refactoring of Pyserini resulted in some module names changing.  This PR updates the compatibility issues in the BM25 reranker, relevance.py and segmentation.py.

Fix Pyserini compatibility issues

---

docs/experiments-CovidQA.md
docs/experiments-msmarco-document.md

Able to replicate CovidQA experiment with identical T5 results but different BM25 results.
```
BM25 NL Question
precision@1	0.15384615384615385
recall@3	0.21865889212827985
recall@50	0.7208778749595076
recall@1000	0.7582928409459021
mrr	0.25329970378011524
mrr@10	0.23344131303314977
BM25 Keyword Query
precision@1	0.15384615384615385
recall@3	0.21865889212827985
recall@50	0.7208778749595076
recall@1000	0.7582928409459021
mrr	0.25441237140238665
mrr@10	0.23493413238311195
```
Able to replicate MSMarco-Document experiment with identical results to doc.
```
After 1st Half
2020-09-08 03:27:22 [INFO] evaluate_document_ranker: precision@1 0.16
2020-09-08 03:27:22 [INFO] evaluate_document_ranker: recall@3    0.44
2020-09-08 03:27:22 [INFO] evaluate_document_ranker: recall@50   0.84
2020-09-08 …
```

Add to MSMarco-Doc/CovidQA Replication Log

---

docs/experiments-CovidQA.md
docs/experiments-msmarco-document.md

CovidQA: All identical except for BM25
MS-MARCO doc: Identical
See comments for detailed replication results

CovidQA + MSMARCO doc Replication log

---

docs/experiments-CovidQA.md
docs/experiments-msmarco-document.md
docs/experiments-msmarco-passage.md

**Colab Environment**
> OS: macOS Catalina Version 10.15.5 (19F101)
> Java: openjdk 11.0.8 2020-07-14
> Python: Python 3.6.9
> GPU: Tesla T4 on Colab
**Replication Results**
> all Identical
**Time taken**
MS MARCO Passage Retrieval:
> monoBERT: 51:25
> monoT5: 37:29
MS MARCO Document Retrieval:
> monoT5 
> first half: 3:56:53
> second half: 4:15:11
CovidQA:
> Random: <1s
> BM25: 9s
> monoT5: 16:05
Issue encountered:
CovidQA replication doc: https://github.com/castorini/pygaggle/blob/master/docs/experiments-CovidQA.md does not have a Data Prep section as https://github.com/castorini/pygaggle/blob/daeb78c8d020112a7824dfd4d487905860372892/docs/experiments-msmarco-passage.md#data-prep, I simply ran the script `sh scripts/update-index.sh` to get the data.

Add replication logs for MSMARCO passage, document and CovidQA.

---

docs/experiments-CovidQA.md
docs/experiments-msmarco-document.md

Finally, replication on Colab through ssh is successful with K80 ....
Colab Environment:
OS: Ubuntu-18.04.3 LTS
Java: 11.0.8
Python: 3.6.9
results are shown below:
+ experiments-msmarco-document(identical with the documents):
Re-Ranking with monoT5:
First half:
Second half:
+ experiments-CovidQA(identical with the documents):
Re-Ranking with Random:
NL Question:
Keyword Query:
Re-Ranking with BM25:
NL Question:
Keyword Query:
Re-Ranking with monoT5:
NL Question:
Keyword Query:

replication results for MSMARCO document and CovidQA.

---

pygaggle/rerank/transformer.py

I did a text replace at one point and must've overwritten these default values
the correct paths are `castorini/monot5-base-msmarco` and `'castorini/monobert-large-msmarco'`. sorry for this!

Fix default args in MonoBERT/T5

---

README.md

I realized we don't have any pointers to MS MARCO and CovidQA documentations on the main page.

Adds links to documentation

---

docs/experiments-CovidQA.md
docs/experiments-msmarco-document.md
docs/experiments-msmarco-passage-subset.md

Colab Environment:
OS: Ubuntu-18.04.3 LTS
Java: 11.0.8
Python: 3.6.9
GPU: Tesla P100
NL Question:
```
❯ python3 -um pygaggle.run.evaluate_kaggle_highlighter --method random \
--dataset data/kaggle-lit-review-0.2.json \
--index-dir indexes/lucene-index-cord19-paragraph-2020-05-12
precision@1     0.0
recall@3        0.0199546485260771
recall@50       0.3247165532879819
recall@1000     1.0
mrr             0.03999734528458418
mrr@10          0.020888672929489253
```
Keyword Query:
```
❯ python3 -um pygaggle.run.evaluate_kaggle_highlighter --method random \
--split kq \
--dataset data/kaggle-lit-review-0.2.json \
--index-dir indexes/lucene-index-cord19-paragraph-2020-05-12
precision@1     0.0
recall@3        0.0199546485260771
recall@50       0.3247165532879819
recall@1000     1.0
mrr …
```

Replication experiement results for CovidQA, MSMARCO document and MSMARCO subset

---

docs/experiments-monot5-tpu.md

I think the TPU document is good for now, refactored to include some results for T5-base, as well as make fixes that were causing it to break earlier (Apparently memory consumption is higher with the newer version of tf, etc, so I switched to 800000 lines split instead 1000000). I tested training/evaluation on T5-base and I was able to replicate similar results as paper.

Refactored TPU documentation

---

docs/experiments-msmarco-passage-entire.md

Compute Canada environment: 
OS: linux CentOS-7
Java 13.0.1
Python 3.6.3 
**Re-Ranking with monoBERT** 
`2020-11-13 14:36:43 [INFO] evaluate_passage_ranker: Reranking:` 
`100%|██████████| 6980/6980 [63:20:00<00:00, 32.66s/it]` 
`2020-11-16 05:56:44 [INFO] evaluate_passage_ranker: precision@1 0.2533` 
`2020-11-16 05:56:44 [INFO] evaluate_passage_ranker: recall@3    0.45093` 
`2020-11-16 05:56:44 [INFO] evaluate_passage_ranker: recall@50   0.80609` 
`2020-11-16 05:56:44 [INFO] evaluate_passage_ranker: recall@1000 0.86289` 
`2020-11-16 05:56:44 [INFO] evaluate_passage_ranker: mrr         0.38789` 
`2020-11-16 05:56:44 [INFO] evaluate_passage_ranker: mrr@10      0.37922` 
**Re-Ranking with monoT5** 
`2020-11-13 14:46:35 [INFO] evaluate_passage_ranker: Reranking:` 
`100%|██████████| 6980/6980 …

Update Replication Log and Refactor Instructions for MS Marco Passage Retreival - Entire Dev Set 

---

pygaggle/model/decode.py
pygaggle/model/tokenize.py
pygaggle/rerank/transformer.py
requirements.txt

for Issue https://github.com/castorini/pygaggle/issues/107
fix transformers v3.x & v4.x conflicts based on https://github.com/huggingface/transformers/releases/tag/v4.0.0-rc-1
fixed:
- `prepare_inputs_for_generation` output types
- tokenizer args, e.g. `padding`, `truncate`
- model forward `return_dict`
- requirements
replicated
- msmarco-passage-subset experiments on MonoBert & MonoT5-base

update transformers==2.10.0 to transformers==4.0.0rc1

---

environment.yml
pygaggle/model/decode.py
pygaggle/model/tokenize.py
pygaggle/rerank/transformer.py
pygaggle/run/evaluate_document_ranker.py
pygaggle/run/evaluate_kaggle_highlighter.py
pygaggle/run/evaluate_passage_ranker.py
pygaggle/run/evaluate_trec_covid_ranker.py
requirements.txt

1. `sentencepiece` need to be installed saperately in transformers 4.0.0 for slow Tokenizers e.g. T5Tokenizer.
2. set `use_fast=False` for Tokenizers to make sure tokenizers have same behavior as before
3. change "max_length" padding for T5 to "longest" padding which gives same result with taking 1/3 time.
replicated msmarco-subset
https://colab.research.google.com/drive/1xt0a-EvGO7zprCoBUjtBQFdB4WL9nwuT?usp=sharing

fix inconsistency re upgrading to transformer 4.0.0 

---

docs/experiments-msmarco-passage-subset.md

Modifying replication log to track that I was successfully able to replicate the monoBERT and monoT5 baseline for a subset of the MSMARCO Passage tasks (available here: https://www.dropbox.com/s/5xa5vjbjle0c8jv/msmarco_ans_small.zip).
I replicated both of these baselines in two environments:
1) Ubuntu 20.04 using a GeForce 940MX, Python 3.8.5, Java 11, CUDA 11.0
2) ComputeCanada supercomputer with Tesla V100, Python 3.8, Java 13, CUDA 10.1
In the second environment, there were no issues obtaining the results.
In the first environment, the following problems were encountered:
1) When running monoBERT baseline, encountered ```ImportError: cannot import name 'AutoModel' from 'transformers'```. See https://github.com/huggingface/transformers/issues/4172 for more details. This was fixed by …

Replication of monoBERT & monoT5 Baselines for MSMARCO Passage Ranking

---

docs/experiments-msmarco-passage-subset.md

**Re-Ranking with monoBERT**
I've got the same results
```
precision@1 0.27619
recall@3    0.42698
recall@50   0.81746
recall@1000 0.84762
mrr         0.4109
mrr@10      0.40268
```
**Re-Ranking with monoT5**
I've got approximately the same results
```
precision@1 0.27619
recall@3    0.4746
recall@50   0.80635
recall@1000 0.84762
mrr         0.39734
mrr@10      0.38983
```
**Issues**
The current commands in the doc give the following error (caused by #127):
```
File "pygaggle/pygaggle/run/evaluate_passage_ranker.py", line 208, in <module>
main()
File "pygaggle/pygaggle/run/evaluate_passage_ranker.py", line 178, in main
options = PassageRankingEvaluationOptions(**vars(args))
File ".../.../pydantic/main.py", line 338, in __init__
raise validation_error …
```

MS MARCO Passage Retrieval - Subset Replication

---

docs/experiments-msmarco-passage-subset.md

GPU: Nvidia GeForce GTX 1060
OS: Ubuntu 20.04.1 LTS
JDK: 11.0.9.1
Maven: 3.6.3
Replicated successfully and without any issues:
Sanity Check
monoBERT
monoT5

Replicated PyGaggle: Neural Ranking Baselines on MS MARCO Passage Retrieval - Dev Subset

---

pygaggle/data/segmentation.py

When replicating fh of "PyGaggle: Baselines on MS MARCO Document Retrieval," I got the error:
It seems that document titles default to None instead of '' (empty string) (see class Text in pygaggle/rerank/base.py), so I added an extra condition in the if statement to prevent type mismatch (pygaggle/data/segmentation.py).
The error from fh of the replication task no longer appears after this change.
However, I got somewhat different results from the replication document results (same as https://github.com/castorini/pygaggle/pull/137#issuecomment-756386914 though):

Fixed Document Title Type Mismatch

---

docs/experiments-msmarco-document.md

**Re-Ranking with monoT5**
Some values are not exactly the same as documented. 
No issues found in replication.
**First Half**
```
precision@1 0.24
recall@3    0.44
recall@50   0.84
recall@1000 0.88
mrr         0.39115
mrr@10      0.38205
```
**Second Half**
```
precision@1 0.24
recall@3    0.36
recall@50   0.76
recall@1000 0.88
mrr         0.32717
mrr@10      0.30778
```

MS MARCO Document Retrieval Replication

---

docs/experiments-monot5-tpu.md

The newer versions of the T5 library simply ignore `--gin_param="tokens_per_batch = 65536" \`:
https://github.com/google-research/text-to-text-transfer-transformer/issues/21

Avoid ignored batch size argument

---

docs/experiments-duot5-tpu.md

The newer versions of the T5 library simply ignore --gin_param="tokens_per_batch = 65536" \:
google-research/text-to-text-transfer-transformer#21

Avoid ignored batch size argument - for duoT5

---

docs/experiments-dpr-reader.md
pygaggle/data/retrieval.py
pygaggle/model/evaluate.py
pygaggle/reader/base.py
pygaggle/reader/dpr_reader.py
pygaggle/run/evaluate_passage_reader.py

Draft for adding a Reader module and DPRReader in PyGaggle (https://github.com/castorini/pygaggle/issues/149).
TODO: Test DPRReader by replicating the results in DPR paper.
**Description of Code**
pygaggle/model/evaluate.py: class ReaderEvaluator - Takes in the examples (query, texts, ground truth answers), predicts answers using the DPRReader, and compares the top answer with the ground truth answers using exact match. Like https://github.com/facebookresearch/DPR/blob/f403c3b3e179e53c0fe68a0718d5dc25371fe5df/train_reader.py#L186.
pygaggle/reader/dpr_reader.py: class DensePassageRetrieverReader - Predicts answers from a query and texts, like in https://huggingface.co/transformers/v3.2.0/_modules/transformers/tokenization_dpr.html.
pygaggle/run/evaluate_passage_reader.py: The main content …

Add DPR Reader

---

docs/experiments-dpr-reader.md
pygaggle/run/evaluate_passage_reader.py

- Clean up output
- Update tools commit
- Print topk accuracies
- Switch to retrieval file only, not directory

Cleanup DPRReader, print topk accuracies

---

pygaggle/model/evaluate.py
pygaggle/reader/dpr_reader.py
pygaggle/run/evaluate_passage_reader.py

Example usage: `python -um pygaggle.run.evaluate_passage_reader --task wikipedia --method dpr --retrieval-file data/run.dpr.nq.single.bf.top100.json --output-dir dpr_predictions --topk-retrieval 10 20 50 --topk-em 10 20 50`
Top 10 EM: 40.581717451523545
Top 20 EM: 40.83102493074792
Top 50 EM: 41.32963988919667
https://colab.research.google.com/drive/18C0HXbvrLBE95kIM37_B6lXdxMLifBLZ#scrollTo=_DBTDM3uv9Hg
Example of Outputted Prediction JSON:
[actual_dpr_predictions.zip](https://github.com/castorini/pygaggle/files/5974728/actual_dpr_predictions.zip)

Add Multi Topk EM

---

pygaggle/model/evaluate.py
pygaggle/reader/dpr_reader.py
pygaggle/reader/reader_settings.py
pygaggle/run/evaluate_passage_reader.py

Example Usage:
`python -um pygaggle.run.evaluate_passage_reader --task wikipedia --retriever score --reader dpr --settings dpr dprfusion_1.0_0.63 gar garfusion_0.32_0.1952 --retrieval-file data/nq-single-test.json --topk-em 20 40`

Add Multi Reader Support

---

docs/experiments-msmarco-passage-subset.md

**Platform:** Colab
**Issues:** Running Torch version 1.8.1, which Colab uses as default raises:
`colab cannot import name 'save_state_warning' from 'torch.optim.lr_scheduler' `
I downgraded PyTorch to 1.5.0 and it worked. 
Details and reproduction results can be found in [the notebook](https://colab.research.google.com/drive/1uYexUCKwGZTS5BQB_FmSgxNrVLnGKc9s?usp=sharing)

finished reproduction

---

requirements.txt

- Add Torch to requirements and specify which version to use.
Versions newer than 1.7.0 do not work because of this change in PyTorch: https://github.com/pytorch/pytorch/pull/46813

Add specific version of Torch to requirements

---

README.md
pygaggle/model/evaluate.py
pygaggle/rerank/base.py
pygaggle/rerank/bm25.py
pygaggle/rerank/identity.py
pygaggle/rerank/random.py
pygaggle/rerank/transformer.py
tests/test_base.py

This PR renames the existing `rerank` function to `rescore`. It also adds a separate `rerank` function that calls `rescore` and sorts the list of texts that `rescore` returns. It maintains the assumption of the ReRanker class (that it doesn't alter the original input list of text).
--------
This PR is a workaround for the replication issue in https://github.com/castorini/pygaggle/pull/184

Add rescore

---

pygaggle/model/tokenize.py

This avoids the following warning message:
```
f"This sequence already has {self.eos_token}. In future versions this behavior may lead to duplicated eos tokens being added."
```

Removes unnecessary eos token

---

pygaggle/rerank/transformer.py
requirements.txt

This PR adds a new reranker based on a MiniLM cross-encoder pretrained on MS-MARCO provided by the SentenceTransformers package. MiniLM-based models are much faster than MonoT5/MonoBERT while maintaining a similar result when compared to MonoT5.
Although it adds a new dependency, SentenceTransformers handles smart batching and other optimizations that otherwise would need to be implemented in PyGaggle. I also added AMP integration for FP16 inference, which should make inferences even faster (I can add this to other models if that's desirable).
Besides MiniLM-based models, there is a [list of supported models](https://huggingface.co/cross-encoder).

Add MiniLM cross-encoder reranker

---

pygaggle/rerank/transformer.py

Following #200, this PR adds AMP inference to MonoT5, DuoT5 and MonoBERT (disabled by default to avoid a performance drop).

Add AMP inference to MonoT5, DuoT5 and MonoBERT

---

docs/experiments-dpr-reader.md

Environment: Compute Canada (Cedar), Memory = 64 GB, GPUs = 1
Updated installation instructions specific to CC, removed the additional command to install `tensorflow_gpu` as tensorflow is already in `requirements.txt`

Replication of DPR experiment 

---

pygaggle/rerank/transformer.py

Adding support for multilingual MonoT5 reranker.
Using AutoModelForSeq2SeqLM() for loading T5/mT5 models.
A list containing the models name with its predictions tokens was added to help users.

Adding support for multilingual MonoT5 reranker

---

pygaggle/data/kaggle.py
pygaggle/data/msmarco.py
pygaggle/data/trec_covid.py

The naming `Random P@1` is confusing for users of pygaggle who are not completely familiar with the codebase. If someone is trying compare P@1 of their first-stage ranker (e.g. BM25) and P@1 after reranking, when they see `Random P@1`, they may interpret it as `FirstStage P@1` (aka. `Existing P@1`). However,  [this line](https://github.com/castorini/pygaggle/blob/master/pygaggle/data/msmarco.py#L121) implies that it is actually `P@K` where `K` is the size of the ranked list (e.g. 1,000). Interpreted differently, it is the expected P@1 of a random ordering of the candidate texts, which after discussing with @ronakice seems to be the intention.
I am not a big fan of the new name I chose `Expected METRIC for Random Ordering` (it seems too long). Other suggestions are welcomed. But clarity is …

changed metric naming for clarification

---

docs/experiments-msmarco-document.md

Updating a broken link, as discussed in https://github.com/castorini/pygaggle/issues/265. I was able to verify this link through the download and extraction steps, but I'm facing several (seemingly unrelated) issues when ranking (ie. starting in the `Re-Ranking with monoT5` section). I will open separate issues for those. I don't know whether this new index will change the results reported in this document, so let me know if this is an issue for this PR!

Update broken link for pre-built MS MARCO index

---

docs/experiments-msmarco-passage-subset.md

Reproduced the neural reranking baselines on the MS MARCO passage subset.
- Ubuntu 18.04.5 LTS
- Python 3.7.13
- GPU: Tesla T4 (Google Colab)
- CUDA Version: 11.6
Ran into the following error when evaluating monoBERT:
```
Traceback (most recent call last):
File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/root/pygaggle/pygaggle/run/evaluate_passage_ranker.py", line 13, in <module>
from pygaggle.rerank.base import Reranker
File "/root/pygaggle/pygaggle/rerank/base.py", line 5, in <module>
from pyserini.search import JSimpleSearcherResult
File "/usr/local/lib/python3.7/dist-packages/pyserini/search/__init__.py", line 20, in <module>
from ._impact_searcher import …
```

Append to MS MARCO Passage Retrieval Subset reproduction log

---

docs/experiments-msmarco-passage-subset.md

Environment
- GPU: Tesla T4 (Colab)
- Python 3.7.13
- Ubuntu 18.04.5 LTS
Also ran into the issue of "No module named faiss"
Resolved with `pip install faiss-gpu`
MonoBert Results
MonoT5 Results

Reproduced msmarco passage retrieval dev subset results

---

pygaggle/rerank/transformer.py

With this parameter we can use different batch sizes, as already possible with other rerankers (e.g. MonoT5), example:
```python
reranker = SentenceTransformersReranker(
pretrained_model_name_or_path='cross-encoder/ms-marco-MiniLM-L-6-v2',
batch_size=50,
)
```

Add batch size parameter to SentenceTransformersReranker

---

pygaggle/qa/fid_reader.py
pygaggle/run/evaluate_fid_reader.py

As per the original FiD paper, text_maxlength i.e. the maximum number of tokens in text segments (question+passage), should be limited to 250. In our codebase, it was being limited to 350. From some testing I did, this did not make a huge difference in results, perhaps because most (question + 100-word passage) text segments were within this limit anyway.

Fix FiD text_maxlength
