docs/experiments-msmarco-passage.md
**Environment**
OS: Debian GNU/Linux 9
Python: 3.7.7
Pytorch: 1.5.0
GPU: Tesla P100
CUDA: 10.1
**Replication Result**
monoBERT
monoT5
=> add replication log

data/kaggle-lit-review-0.2.json, pygaggle/data/kaggle.py, pygaggle/data/msmarco.py, pygaggle/data/relevance.py, pygaggle/run/evaluate_kaggle_highlighter.py
- Add 24 query--document pairs
- Remove duplicated example
=> Update dataset to 0.2

setup.cfg
Just clarifying to flake8 that max line length is 100 as per discussions!
=> clarify to flake8 max len 100

docs/experiments-msmarco-passage.md, pygaggle/logger.py, pygaggle/run/evaluate_passage_ranker.py
fix indentation to meet flake8 requirement
ignore logs from transformers globally.
remove duplicate evaluate info
=> ignore logs from transformers

.gitmodules
Seems like it didn't properly load the submodule last time around and was still having old eval. This time looks good.
=> Fix tools 1

docs/experiments-msmarco-document.md, requirements.txt
=> Update replication log and requirements doc

docs/experiments-msmarco-document.md
Replicated identical results on msmarco document experiment.
First half:
Second half:
=> Update Replication Log

pygaggle/model/writer.py
=> change raw to metadata

docs/experiments-msmarco-passage.md
=> revert unnecessary writeup.

docs/experiments-msmarco-passage.md
OS: `Ubuntu 18.04.3 LTS`
Java: `openjdk 11.0.8 2020-07-14`
Python: `Python 3.6.9`
Tested with `Tesla T4`
BERT reranking: Identical
```
2020-09-09 01:24:16 [INFO] evaluate_passage_ranker: Reranking:
100% 105/105 [51:33<00:00, 29.46s/it]
2020-09-09 02:15:50 [INFO] evaluate_passage_ranker: precision@1 0.27619
2020-09-09 02:15:50 [INFO] evaluate_passage_ranker: recall@3    0.42698
2020-09-09 02:15:50 [INFO] evaluate_passage_ranker: recall@50   0.81746
2020-09-09 02:15:50 [INFO] evaluate_passage_ranker: recall@1000 0.84762
2020-09-09 02:15:50 [INFO] evaluate_passage_ranker: mrr         0.4109
2020-09-09 02:15:50 [INFO] evaluate_passage_ranker: mrr@10      0.40268
```
T5 reranking: Identical
```
2020-09-09 02:20:09 [INFO] evaluate_passage_ranker: Reranking:
100% 105/105 [1:12:39<00:00, …
```
=> MS-MARCO passage replication log

pygaggle/model/writer.py
add writer to write in trec format
=> add trec writer

docs/experiments-CovidQA.md, docs/experiments-msmarco-document.md, docs/experiments-msmarco-passage.md
Replication result for pygaggle
**MS MARCO Passage Retrieval (identical)**
Environment
OS: Windows 10
Python: 3.8.2
Java: 11.0.8
GPU: RTX 2070S
monoBERT:
monoT5:
**MS MARCO Document Retrieval (identical)**
Environment
OS: Windows 10
Python: 3.8.2
Java: 11.0.8
GPU: RTX 2070S
First half:
Second half:
**CovidQA (identical)**
Environment
OS: Ubuntu 18.04.3 LTS (Colab)
Python: 3.6.9
Java: 11.0.8
GPU: T4
Random NL:
Random KQ:
BM25 NL:
BM25 KQ:
T5 NL:
T5 KQ:
=> CovidQA replications

docs/experiments-msmarco-document.md, docs/experiments-msmarco-passage-entire.md, docs/experiments-msmarco-passage-subset.md
Compute Canada environment: 
OS: linux CentOS-7
Java 13.0.1
Python 3.7.4
No issues encountered and same results are reproduced.
=> replication experiment log for msmarco on Compute Canada

docs/experiments-msmarco-passage-entire.md
Need to load java module in the new environment so as to install pygaggle.
=> Add load commend to CC instruction

docs/experiments-msmarco-passage-subset.md
OS: Ubuntu 18.04 LTS 64-bit x86
Java: openjdk 11
Python: 3.7.4
GPU: Tesla T4
**monoBERT Replication Results**
`2020-11-05 21:03:01 [INFO] evaluate_passage_ranker: precision@1 0.27619`
`2020-11-05 21:03:01 [INFO] evaluate_passage_ranker: recall@3    0.42698`
`2020-11-05 21:03:01 [INFO] evaluate_passage_ranker: recall@50   0.81746`
`2020-11-05 21:03:01 [INFO] evaluate_passage_ranker: recall@1000 0.84762`
`2020-11-05 21:03:01 [INFO] evaluate_passage_ranker: mrr         0.4109`
`2020-11-05 21:03:01 [INFO] evaluate_passage_ranker: mrr@10      0.40268`
**monoT5 Replication Results**
`2020-11-05 22:17:05 [INFO] evaluate_passage_ranker: precision@1 0.26667`
`2020-11-05 22:17:05 [INFO] evaluate_passage_ranker: recall@3    0.46032`
`2020-11-05 22:17:05 [INFO] evaluate_passage_ranker: recall@50 …
=> Successful Replication for MS MARCO passage

pygaggle/logger.py
=> clean filelock output

experiments/verT5erini/README.md, experiments/verT5erini/create_full_pipe_eval.py, experiments/vert5erini/requirements.txt
Public-facing links, naming conventions
=> refactor scifact 1

docs/experiments-CovidQA.md
=> CovidQA Replication

docs/experiments-msmarco-passage-entire.md
Same results were reproduced.
No issues were found.
=> MS MARCO Passage Retrieval - Entire Set Replication

docs/experiments-msmarco-passage-entire.md
Replicated successfully on Tesla V100 on Compute Canada.
=> PyGaggle: Neural Ranking Baselines on MS MARCO Passage Retrieval - Entire Dev Set

docs/experiments-msmarco-document.md
Replicated successfully:
fh
sh
=> Replicated PyGaggle: Baselines on MS MARCO Document Retrieval

README.md, scripts/update-index.sh
=> Fix update-index file, remove CovidQA specific instructions from README

pygaggle/data/msmarco.py, pygaggle/data/retrieval.py, pygaggle/model/decode.py, pygaggle/model/evaluate.py, pygaggle/model/writer.py, pygaggle/reader/base.py, pygaggle/rerank/transformer.py, pygaggle/run/evaluate_document_ranker.py, pygaggle/run/evaluate_passage_reader.py, pygaggle/settings.py, scripts/train_d2q.py
Flake-8 Compliancy stuff, focusing on cleaning up DPR code so far.
=> cleanup code, primarily DPR

docs/experiments-dpr-reader.md, pygaggle/reader/dpr_reader.py
- Around 3x speedup in reader inference
- Reduce slowdown factor when returning more passages in decode_best_spans
- Updated replication document to reflect added retrieval and larger topk passages support
=> Optimize decode_best_spans

README.md, pygaggle/reader/base.py, setup.py
Oops didn't properly check the reader side of things.
=> Release: v0.0.3.1

README.md, pygaggle/rerank/transformer.py
Addresses https://github.com/castorini/pygaggle/issues/173
=> Fix rerank function

experiments/vert5erini/README.md
update each step evaluate for scifact.
still need to add results later
=> update vert5erini doc

docs/experiments-msmarco-passage-subset.md
The reproduce success! Here is the produce results
I encounter some issues during set up torch with CUDA locally. I would post here for reference.
1. Don't use ubuntu WSL on windows. As decribed here [https://docs.nvidia.com/cuda/wsl-user-guide/index.html#installing-nvidia-drivers](url), it requires windows os build to be 20145 or later which is Windows 11.
2. The combination among torch, CUDA and Nvidia driver is missive. Please look at this [https://pytorch.org/get-started/previous-versions/](url)
=> reproduce MS MARCO Passage Retrieval by zizeng

experiments/Vera/README.md
Add commands used to replicate Vera for TREC 2020 Health Misinformation Track.
=> Create README.md for Vera Replication

docs/experiments-msmarco-passage-subset.md
Successfully reproduced results
Ubuntu 20.04.03 LTS
Python 3.6.13
=> Reproduced MSMARCO passage retrieval (subset) experiment

pygaggle/rerank/transformer.py
We are adding support for [mMARCO v2](https://github.com/unicamp-dl/mMARCO).
=> Adding support to mMARCO v2

pygaggle/rerank/transformer.py
Fixed dict with model names. As PR #247 is closed, created a new one. @rodrigonogueira4
=> Adding support to mMARCO v2-fix

pygaggle/model/evaluate.py, pygaggle/qa/fid/model.py, pygaggle/qa/fid_reader.py, pygaggle/run/evaluate_fid_ranker.py, pygaggle/run/evaluate_passage_reader.py
Notebook:
https://colab.research.google.com/drive/1DLX59bJvFjdv3wQM6wU0DDlcsaJzIAJ-#scrollTo=69zZa1KEPp5U
=> Refactor fid reader

pygaggle/rerank/base.py, requirements.txt
Unfortunately, with this change, Pyserini 0.16.0 or above must be used
=> Add support for Pyserini 0.16.0

docs/experiments-msmarco-passage-subset.md
Reproduced results on Ubuntu 18.04, GeForce RTX 3070
=> Result Reproduction
